[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "sh start.sh"

[variables]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"
